### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by naofum**
Hello!

### CODE REVIEW

**Comment by dalekunce** [comment]
@naofum this is fantastic. @hallahan should be the one to review and merge this in.

**Comment by hallahan** [comment]
This is awesome! I'll be reviewing this. Thanks!

**Comment by danbjoseph** [comment]
@hallahan were you able to review this? can we merge?

**Comment by hallahan** [comment]
I don't have my Android dev stuff setup at the moment. Is there any way you can just try it out? Do you by any chance have the dev environment set up?

**Comment by danbjoseph** [comment]
@rajsingh8220 any chance you can test this?

**Comment by rajsingh8220** [comment]
@danbjoseph I have tested the branch `japanese-translation`
My git config to download the project:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/naofum/OpenMapKitAndroid.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "japanese-translation"]
	remote = origin
	merge = refs/heads/japanese-translation
```
### Main Menu
attach1

### App Nav
attach2

**Comment by danbjoseph** [comment]
thank @naofum, sorry it took so long to merge!

**Pull request merged**
